version: 2.1

orbs:
  azure-aks: circleci/azure-aks@0.3.0
jobs:
  build-and-deploy:
    docker:
      - image: ubuntu-2204:2023.10.1
    steps:
      - checkout

      - run:
          name: Install Azure CLI
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - run:
          name: Install kubectl
          command: |
            sudo az aks install-cli

      - run:
          name: Azure Login
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - run:
          name: Build Docker Images
          command: |
            docker build -t $ACR_NAME.azurecr.io/main-service:latest -f Dockerfile.main .
            docker build -t $ACR_NAME.azurecr.io/sidecar-service:latest -f Dockerfile.sidecar .

      - run:
          name: Azure ACR Login
          command: |
            az acr login --name $ACR_NAME

      - run:
          name: Push Images to ACR
          command: |
            docker push $ACR_NAME.azurecr.io/main-service:latest
            docker push $ACR_NAME.azurecr.io/sidecar-service:latest

      - run:
          name: Attach ACR to AKS
          command: |
            az aks update -n $AKS_CLUSTER_NAME -g $RESOURCE_GROUP_NAME --attach-acr $ACR_NAME

      - run:
          name: Get AKS credentials
          command: |
            az aks get-credentials --resource-group $RESOURCE_GROUP_NAME --name $AKS_CLUSTER_NAME

      - run:
          name: Deploy to AKS
          command: |
            kubectl apply -f k8s/main-deployment.yaml
            kubectl apply -f k8s/main-service.yaml
            kubectl apply -f k8s/sidecar-deployment.yaml
            kubectl apply -f k8s/sidecar-service.yaml

workflows:
  deploy:
    jobs:
      - build-and-deploy
